package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func Calcium(output string) {
	lines := strings.Split(calciumSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Calcium, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 8
		a := ages[i]
		list = append(list,
			newCalcium(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+4]),
			newCalcium(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+4:j+8]),
		)
	}

	list2 := make([]data.Calcium, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newCalciumWithOption(d, data.OptionEarlyPregnancy),
			newCalciumWithOption(d, data.OptionMidPregnancy),
			newCalciumWithOption(d, data.OptionLatePregnancy),
			newCalciumWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func CalciumList() []Calcium {\n")
	g.MustWrite("    return []Calcium {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newCalcium(g data.Gender, from, to data.Age, o data.Option, cols []string) data.Calcium {
	return data.Calcium{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
		UL:     data.NilFloatFromString(cols[3]),
	}
}

func newCalciumWithOption(in data.Calcium, o data.Option) data.Calcium {
	d := data.Calcium{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
		UL:     in.UL,
	}
	return d
}

// PDF 315 ページの「カルシウムの食事摂取基準」のコピペ
const calciumSrc = `0 ～ 5 （月） ─ ─ 200 ─ ─ ─ 200 ─
6 ～11（月） ─ ─ 250 ─ ─ ─ 250 ─
1 ～ 2 （歳） 350 450 ─ ─ 350 400 ─ ─
3 ～ 5 （歳） 500 600 ─ ─ 450 550 ─ ─
6 ～ 7 （歳） 500 600 ─ ─ 450 550 ─ ─
8 ～ 9 （歳） 550 650 ─ ─ 600 750 ─ ─
10～11（歳） 600 700 ─ ─ 600 750 ─ ─
12～14（歳） 850 1,000 ─ ─ 700 800 ─ ─
15～17（歳） 650 800 ─ ─ 550 650 ─ ─
18～29（歳） 650 800 ─ 2,500 550 650 ─ 2,500
30～49（歳） 600 750 ─ 2,500 550 650 ─ 2,500
50～64（歳） 600 750 ─ 2,500 550 650 ─ 2,500
65～74（歳） 600 750 ─ 2,500 550 650 ─ 2,500
75 以上（歳） 600 700 ─ 2,500 500 600 ─ 2,500
妊婦（付加量） +0 +0 ─ ─
授乳婦（付加量） +0 +0 ─ ─`
