package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

// Carbohydrates は PDF 171 ページの「炭水化物の食事摂取基準」をパースして Go の構造体を作成します
func Carbohydrates(output string) {
	lines := strings.Split(carbohydratesSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Carbohydrates, 0)
	for i := 0; i <= 13; i++ {
		cols := strings.Split(lines[i], " ")
		j := len(cols) - 2
		a := ages[i]
		list = append(list,
			newCarbohydrates(data.GenderMale, a[0], a[1], data.OptionNone, cols[j]),
			newCarbohydrates(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+1]),
		)
	}

	list2 := make([]data.Carbohydrates, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		if d.DG.Min.Valid && d.DG.Max.Valid {
			list2 = append(list2,
				newCarbohydratesWithOption(d, data.OptionEarlyPregnancy),
				newCarbohydratesWithOption(d, data.OptionMidPregnancy),
				newCarbohydratesWithOption(d, data.OptionLatePregnancy),
				newCarbohydratesWithOption(d, data.OptionBreastfeeding),
			)
		}
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func CarbohydratesList() []Carbohydrates {\n")
	g.MustWrite("    return []Carbohydrates {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newCarbohydrates(g data.Gender, from, to data.Age, o data.Option, col string) data.Carbohydrates {
	return data.Carbohydrates{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		DG:     newCarbohydratesDG(col),
	}
}

func newCarbohydratesDG(s string) data.NilFloatRange {
	pair := strings.Split(s, "～")
	if len(pair) == 2 {
		return data.NilFloatRange{
			Min: data.NilFloatFromString(pair[0]),
			Max: data.NilFloatFromString(pair[1]),
		}
	}
	return data.NilFloatRange{
		Min: data.NilFloat{},
		Max: data.NilFloat{},
	}
}

func newCarbohydratesWithOption(in data.Carbohydrates, o data.Option) data.Carbohydrates {
	d := data.Carbohydrates{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		DG:     in.DG,
	}
	return d
}

// PDF 171 ページの「炭水化物の食事摂取基準」
const carbohydratesSrc = `0 ～ 5 （月） ─ ─
6 ～11（月） ─ ─
1 ～ 2 （歳） 50～65 50～65
3 ～ 5 （歳） 50～65 50～65
6 ～ 7 （歳） 50～65 50～65
8 ～ 9 （歳） 50～65 50～65
10～11（歳） 50～65 50～65
12～14（歳） 50～65 50～65
15～17（歳） 50～65 50～65
18～29（歳） 50～65 50～65
30～49（歳） 50～65 50～65
50～64（歳） 50～65 50～65
65～74（歳） 50～65 50～65
75 以上（歳） 50～65 50～65
妊　婦 50～65
授乳婦 50～65`
