package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func Chromium(output string) {
	lines := strings.Split(chromiumSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Chromium, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 4
		a := ages[i]
		list = append(list,
			newChromium(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+2]),
			newChromium(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+2:j+4]),
		)
	}

	list2 := make([]data.Chromium, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newChromiumWithOption(d, data.OptionEarlyPregnancy),
			newChromiumWithOption(d, data.OptionMidPregnancy),
			newChromiumWithOption(d, data.OptionLatePregnancy),
			newChromiumWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func ChromiumList() []Chromium {\n")
	g.MustWrite("    return []Chromium {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newChromium(g data.Gender, from, to data.Age, o data.Option, cols []string) data.Chromium {
	return data.Chromium{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		AI:     data.NilFloatFromString(cols[0]),
		UL:     data.NilFloatFromString(cols[1]),
	}
}

func newChromiumWithOption(in data.Chromium, o data.Option) data.Chromium {
	d := data.Chromium{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		AI:     in.AI,
		UL:     in.UL,
	}
	var ai float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ai = 10
	case data.OptionBreastfeeding:
		ai = 10
	}
	d.AI = data.NilFloat{Float: ai, Valid: true}
	return d
}

// PDF 379 ページの「クロムの食事摂取基準」のコピペ
const chromiumSrc = `0 ～ 5 	（月） 0.8 ─ 0.8 ─
6 ～11（月） 1.0 ─ 1.0 ─
1 ～ 2 	（歳） ─ ─ ─ ─
3 ～ 5 	（歳） ─ ─ ─ ─
6 ～ 7 	（歳） ─ ─ ─ ─
8 ～ 9 	（歳） ─ ─ ─ ─
10～11（歳） ─ ─ ─ ─
12～14（歳） ─ ─ ─ ─
15～17（歳） ─ ─ ─ ─
18～29（歳） 10 500 10 500
30～49（歳） 10 500 10 500
50～64（歳） 10 500 10 500
65～74（歳） 10 500 10 500
75 以上（歳） 10 500 10 500
妊　婦 10 ─
授乳婦 10 ─`
