package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

// Iodine は PDF 377 ページの「ヨウ素の食事摂取基準」をパースして Go の構造体を作成します
func Iodine(output string) {
	lines := strings.Split(iodineSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Iodine, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 8
		a := ages[i]
		list = append(list,
			newIodine(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+4]),
			newIodine(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+4:j+8]),
		)
	}

	list2 := make([]data.Iodine, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newIodineWithOption(d, data.OptionEarlyPregnancy),
			newIodineWithOption(d, data.OptionMidPregnancy),
			newIodineWithOption(d, data.OptionLatePregnancy),
			newIodineWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func IodineList() []Iodine {\n")
	g.MustWrite("    return []Iodine {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newIodine(g data.Gender, from, to data.Age, o data.Option, cols []string) data.Iodine {
	return data.Iodine{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
		UL:     data.NilFloatFromString(cols[3]),
	}
}

func newIodineWithOption(in data.Iodine, o data.Option) data.Iodine {
	d := data.Iodine{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
		UL:     in.UL,
	}
	var ear, rda, ul float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ear, rda, ul = 75, 110, 2000
	case data.OptionBreastfeeding:
		ear, rda, ul = 100, 140, 2000
	}
	if d.EAR.Valid {
		d.EAR.Float += ear
	}
	if d.RDA.Valid {
		d.RDA.Float += rda
	}
	if d.UL.Valid {
		d.UL.Float = ul
	}
	return d
}

const iodineSrc = `0 ～ 5 	（月） ─ ─ 100 250 ─ ─ 100 250
6 ～11（月） ─ ─ 130 250 ─ ─ 130 250
1 ～ 2 	（歳） 35 50 ─ 300 35 50 ─ 300
3 ～ 5 	（歳） 45 60 ─ 400 45 60 ─ 400
6 ～ 7 	（歳） 55 75 ─ 550 55 75 ─ 550
8 ～ 9 	（歳） 65 90 ─ 700 65 90 ─ 700
10～11（歳） 80 110 ─ 900 80 110 ─ 900
12～14（歳） 95 140 ─ 2,000 95 140 ─ 2,000
15～17（歳） 100 140 ─ 3,000 100 140 ─ 3,000
18～29（歳） 95 130 ─ 3,000 95 130 ─ 3,000
30～49（歳） 95 130 ─ 3,000 95 130 ─ 3,000
50～64（歳） 95 130 ─ 3,000 95 130 ─ 3,000
65～74（歳） 95 130 ─ 3,000 95 130 ─ 3,000
75 以上（歳） 95 130 ─ 3,000 95 130 ─ 3,000
妊婦（付加量） ＋75 ＋110 ─ ─ 1
授乳婦（付加量） ＋100 ＋140 ─ ─`
