package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func Magnesium(output string) {
	lines := strings.Split(magnesiumSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Magnesium, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 8
		a := ages[i]
		list = append(list,
			newMagnesium(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+4]),
			newMagnesium(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+4:j+8]),
		)
	}

	list2 := make([]data.Magnesium, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newMagnesiumWithOption(d, data.OptionEarlyPregnancy),
			newMagnesiumWithOption(d, data.OptionMidPregnancy),
			newMagnesiumWithOption(d, data.OptionLatePregnancy),
			newMagnesiumWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func MagnesiumList() []Magnesium {\n")
	g.MustWrite("    return []Magnesium {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newMagnesium(g data.Gender, from, to data.Age, o data.Option, cols []string) data.Magnesium {
	return data.Magnesium{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
	}
}

func newMagnesiumWithOption(in data.Magnesium, o data.Option) data.Magnesium {
	d := data.Magnesium{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
	}
	var ear, rda float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ear, rda = 30, 40
	case data.OptionBreastfeeding:
		ear, rda = 0, 0
	}
	if d.EAR.Valid {
		d.EAR.Float += ear
	}
	if d.RDA.Valid {
		d.RDA.Float += rda
	}
	return d
}

// PDF 316 ページの「カルシウムの食事摂取基準」のコピペ
const magnesiumSrc = `0 ～ 5 （月） ─ ─ 20 ─ ─ ─ 20 ─
6 ～11（月） ─ ─ 60 ─ ─ ─ 60 ─
1 ～ 2 （歳） 60 70 ─ ─ 60 70 ─ ─
3 ～ 5 （歳） 80 100 ─ ─ 80 100 ─ ─
6 ～ 7 （歳） 110 130 ─ ─ 110 130 ─ ─
8 ～ 9 （歳） 140 170 ─ ─ 140 160 ─ ─
10～11（歳） 180 210 ─ ─ 180 220 ─ ─
12～14（歳） 250 290 ─ ─ 240 290 ─ ─
15～17（歳） 300 360 ─ ─ 260 310 ─ ─
18～29（歳） 280 340 ─ ─ 230 270 ─ ─
30～49（歳） 310 370 ─ ─ 240 290 ─ ─
50～64（歳） 310 370 ─ ─ 240 290 ─ ─
65～74（歳） 290 350 ─ ─ 230 280 ─ ─
75 以上（歳） 270 320 ─ ─ 220 260 ─ ─
妊婦（付加量） ＋30 ＋40 ─ ─
授乳婦（付加量） ＋0 ＋0 ─ ─`
