package main

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func Niacin(output string) {
	lines := strings.Split(niacinSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Niacin, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		r := regexp.MustCompile(`（\d+）`)
		line = r.ReplaceAllString(line, "")
		cols := strings.Split(line, " ")
		j := len(cols) - 8
		a := ages[i]
		list = append(list,
			newNiacin(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+4]),
			newNiacin(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+4:j+8]),
		)
	}

	list2 := make([]data.Niacin, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		if d.EAR.Valid && d.RDA.Valid {
			list2 = append(list2,
				newNiacinWithOption(d, data.OptionEarlyPregnancy),
				newNiacinWithOption(d, data.OptionMidPregnancy),
				newNiacinWithOption(d, data.OptionLatePregnancy),
				newNiacinWithOption(d, data.OptionBreastfeeding),
			)
		}
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func NiacinList() []Niacin {\n")
	g.MustWrite("    return []Niacin {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newNiacin(g data.Gender, from, to data.Age, o data.Option, cols []string) data.Niacin {
	return data.Niacin{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
		UL:     data.NilFloatFromString(cols[3]),
	}
}

func newNiacinWithOption(in data.Niacin, o data.Option) data.Niacin {
	d := data.Niacin{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
		UL:     in.UL,
	}
	var ear, rda float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ear, rda = 0, 0
	case data.OptionBreastfeeding:
		ear, rda = 3, 3
	}
	if d.EAR.Valid {
		d.EAR.Float += ear
	}
	if d.RDA.Valid {
		d.RDA.Float += rda
	}
	return d
}

// PDF 266 ページの「ナイアシンの食事摂取基準」のコピペ
const niacinSrc = `0 ～ 5 （月）4 ─ ─ 2 ─ ─ ─ 2 ─
6 ～11（月） ─ ─ 3 ─ ─ ─ 3 ─
1 ～ 2 （歳） 5 6 ─ 60（15） 4 5 ─ 60（15）
3 ～ 5 （歳） 6 8 ─ 80（20） 6 7 ─ 80（20）
6 ～ 7 （歳） 7 9 ─ 100（30） 7 8 ─ 100（30）
8 ～ 9 （歳） 9 11 ─ 150（35） 8 10 ─ 150（35）
10～11（歳） 11 13 ─ 200（45） 10 10 ─ 150（45）
12～14（歳） 12 15 ─ 250（60） 12 14 ─ 250（60）
15～17（歳） 14 17 ─ 300（70） 11 13 ─ 250（65）
18～29（歳） 13 15 ─ 300（80） 9 11 ─ 250（65）
30～49（歳） 13 15 ─ 350（85） 10 12 ─ 250（65）
50～64（歳） 12 14 ─ 350（85） 9 11 ─ 250（65）
65～74（歳） 12 14 ─ 300（80） 9 11 ─ 250（65）
75 以上（歳） 11 13 ─ 300（75） 9 10 ─ 250（60）
妊婦（付加量） ＋0 ＋0 ─ ─
授乳婦（付加量） ＋3 ＋3 ─ ─`
