package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func Omega6FattyAcids(output string) {
	lines := strings.Split(omega6FattyAcidsSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Omega6FattyAcids, 0)
	for i := 0; i <= 13; i++ {
		cols := strings.Split(lines[i], " ")
		j := len(cols) - 2
		a := ages[i]
		list = append(list,
			newOmega6FattyAcids(data.GenderMale, a[0], a[1], data.OptionNone, cols[j]),
			newOmega6FattyAcids(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+1]),
		)
	}

	list2 := make([]data.Omega6FattyAcids, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newOmega6FattyAcidsWithOption(d, data.OptionEarlyPregnancy),
			newOmega6FattyAcidsWithOption(d, data.OptionMidPregnancy),
			newOmega6FattyAcidsWithOption(d, data.OptionLatePregnancy),
			newOmega6FattyAcidsWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func Omega6FattyAcidsList() []Omega6FattyAcids {\n")
	g.MustWrite("    return []Omega6FattyAcids {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newOmega6FattyAcids(g data.Gender, from, to data.Age, o data.Option, col string) data.Omega6FattyAcids {
	return data.Omega6FattyAcids{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		AI:     data.NilFloatFromString(col),
	}
}

func newOmega6FattyAcidsWithOption(in data.Omega6FattyAcids, o data.Option) data.Omega6FattyAcids {
	d := data.Omega6FattyAcids{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		AI:     in.AI,
	}
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		d.AI.Float = 9
	case data.OptionBreastfeeding:
		d.AI.Float = 10
	}
	return d
}

// PDF 158 ページの「n─6 系脂肪酸の食事摂取基準」のコピペ
const omega6FattyAcidsSrc = `0 ～ 5 （月） 4 4
6 ～11（月） 4 4
1 ～ 2 （歳） 4 4
3 ～ 5 （歳） 6 6
6 ～ 7 （歳） 8 7
8 ～ 9 （歳） 8 7
10～11（歳） 10 8
12～14（歳） 11 9
15～17（歳） 13 9
18～29（歳） 11 8
30～49（歳） 10 8
50～64（歳） 10 8
65～74（歳） 9 8
75 以上（歳） 8 7
妊　婦 9
授乳婦 10`
