package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func Phosphorus(output string) {
	lines := strings.Split(phosphorusSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Phosphorus, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 4
		a := ages[i]
		list = append(list,
			newPhosphorus(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+2]),
			newPhosphorus(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+2:j+4]),
		)
	}

	list2 := make([]data.Phosphorus, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newPhosphorusWithOption(d, data.OptionEarlyPregnancy),
			newPhosphorusWithOption(d, data.OptionMidPregnancy),
			newPhosphorusWithOption(d, data.OptionLatePregnancy),
			newPhosphorusWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func PhosphorusList() []Phosphorus {\n")
	g.MustWrite("    return []Phosphorus {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newPhosphorus(g data.Gender, from, to data.Age, o data.Option, cols []string) data.Phosphorus {
	return data.Phosphorus{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		AI:     data.NilFloatFromString(cols[0]),
		UL:     data.NilFloatFromString(cols[1]),
	}
}

func newPhosphorusWithOption(in data.Phosphorus, o data.Option) data.Phosphorus {
	d := data.Phosphorus{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		AI:     in.AI,
		UL:     in.UL,
	}
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy, data.OptionBreastfeeding:
		d.AI.Float = 800
	}
	return d
}

// PDF 317 ページの「リンの食事摂取基準」のコピペ
const phosphorusSrc = `0 ～ 5 （月） 120 ─ 120 ─
6 ～11（月） 260 ─ 260 ─
1 ～ 2 （歳） 500 ─ 500 ─
3 ～ 5 （歳） 700 ─ 700 ─
6 ～ 7 （歳） 900 ─ 800 ─
8 ～ 9 （歳） 1,000 ─ 1,000 ─
10～11（歳） 1,100 ─ 1,000 ─
12～14（歳） 1,200 ─ 1,000 ─
15～17（歳） 1,200 ─ 900 ─
18～29（歳） 1,000 3,000 800 3,000
30～49（歳） 1,000 3,000 800 3,000
50～64（歳） 1,000 3,000 800 3,000
65～74（歳） 1,000 3,000 800 3,000
75 以上（歳） 1,000 3,000 800 3,000
妊　婦 800 ─
授乳婦 800 ─`
