package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

// VitaminA は 212 ページの「ビタミン A の食事摂取基準」をパースして Go の構造体を作成します
func VitaminA(output string) {
	lines := strings.Split(vitaminASrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.VitaminA, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 8
		a := ages[i]
		list = append(list,
			newVitaminA(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+4]),
			newVitaminA(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+4:j+8]),
		)
	}

	list2 := make([]data.VitaminA, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		if d.EAR.Valid && d.RDA.Valid {
			list2 = append(list2,
				newVitaminAWithOption(d, data.OptionEarlyPregnancy),
				newVitaminAWithOption(d, data.OptionMidPregnancy),
				newVitaminAWithOption(d, data.OptionLatePregnancy),
				newVitaminAWithOption(d, data.OptionBreastfeeding),
			)
		}
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func VitaminAList() []VitaminA {\n")
	g.MustWrite("    return []VitaminA {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newVitaminA(g data.Gender, from, to data.Age, o data.Option, cols []string) data.VitaminA {
	return data.VitaminA{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
		UL:     data.NilFloatFromString(cols[3]),
	}
}

func newVitaminAWithOption(in data.VitaminA, o data.Option) data.VitaminA {
	d := data.VitaminA{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
		UL:     in.UL,
	}
	var ear, rda float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy:
		ear, rda = 0, 0
	case data.OptionLatePregnancy:
		ear, rda = 60, 80
	case data.OptionBreastfeeding:
		ear, rda = 300, 450
	}
	if d.EAR.Valid {
		d.EAR.Float += ear
	}
	if d.RDA.Valid {
		d.RDA.Float += rda
	}
	return d
}

const vitaminASrc = `0 ～ 5 （月） ─ ─ 300 600 ─ ─ 300 600
6 ～11（月） ─ ─ 400 600 ─ ─ 400 600
1 ～ 2 （歳） 300 400 ─ 600 250 350 ─ 600
3 ～ 5 （歳） 350 450 ─ 700 350 500 ─ 850
6 ～ 7 （歳） 300 400 ─ 950 300 400 ─ 1,200
8 ～ 9 （歳） 350 500 ─ 1,200 350 500 ─ 1,500
10～11（歳） 450 600 ─ 1,500 400 600 ─ 1,900
12～14（歳） 550 800 ─ 2,100 500 700 ─ 2,500
15～17（歳） 650 900 ─ 2,500 500 650 ─ 2,800
18～29（歳） 600 850 ─ 2,700 450 650 ─ 2,700
30～49（歳） 650 900 ─ 2,700 500 700 ─ 2,700
50～64（歳） 650 900 ─ 2,700 500 700 ─ 2,700
65～74（歳） 600 850 ─ 2,700 500 700 ─ 2,700
75 以上（歳） 550 800 ─ 2,700 450 650 ─ 2,700
妊婦（付加量）初期 ＋0 ＋0 ─ ─
　　　　　中期 ＋0 ＋0 ─ ─
　　　　　　後期 ＋60 ＋80 ─ ─
授乳婦（付加量） ＋300 ＋450 ─ ─`
