package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func VitaminB12(output string) {
	lines := strings.Split(vitaminB12Src, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 8}},
		{{Month: 9}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.VitaminB12, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 6
		a := ages[i]
		list = append(list,
			newVitaminB12(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+3]),
			newVitaminB12(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+3:j+6]),
		)
	}

	list2 := make([]data.VitaminB12, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		if d.EAR.Valid && d.RDA.Valid {
			list2 = append(list2,
				newVitaminB12WithOption(d, data.OptionEarlyPregnancy),
				newVitaminB12WithOption(d, data.OptionMidPregnancy),
				newVitaminB12WithOption(d, data.OptionLatePregnancy),
				newVitaminB12WithOption(d, data.OptionBreastfeeding),
			)
		}
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func VitaminB12List() []VitaminB12 {\n")
	g.MustWrite("    return []VitaminB12 {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newVitaminB12(g data.Gender, from, to data.Age, o data.Option, cols []string) data.VitaminB12 {
	return data.VitaminB12{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
	}
}

func newVitaminB12WithOption(in data.VitaminB12, o data.Option) data.VitaminB12 {
	d := data.VitaminB12{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
	}
	var ear, rda float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ear, rda = 0.3, 0.4
	case data.OptionBreastfeeding:
		ear, rda = 0.7, 0.8
	}
	if d.EAR.Valid {
		d.EAR.Float += ear
	}
	if d.RDA.Valid {
		d.RDA.Float += rda
	}
	return d
}

// PDF 268 ページの「ビタミン B12 の食事摂取基準」のコピペ
const vitaminB12Src = `0 ～ 5 （月） ─ ─ 0.4 ─ ─ 0.4
6 ～11（月） ─ ─ 0.5 ─ ─ 0.5
1 ～ 2 （歳） 0.8 0.9 ─ 0.8 0.9 ─
3 ～ 5 （歳） 0.9 1.1 ─ 0.9 1.1 ─
6 ～ 7 （歳） 1.1 1.3 ─ 1.1 1.3 ─
8 ～ 9 （歳） 1.3 1.6 ─ 1.3 1.6 ─
10～11（歳） 1.6 1.9 ─ 1.6 1.9 ─
12～14（歳） 2.0 2.4 ─ 2.0 2.4 ─
15～17（歳） 2.0 2.4 ─ 2.0 2.4 ─
18～29（歳） 2.0 2.4 ─ 2.0 2.4 ─
30～49（歳） 2.0 2.4 ─ 2.0 2.4 ─
50～64（歳） 2.0 2.4 ─ 2.0 2.4 ─
65～74（歳） 2.0 2.4 ─ 2.0 2.4 ─
75 以上（歳） 2.0 2.4 ─ 2.0 2.4 ─
妊婦（付加量） ＋0.3 ＋0.4 ─
授乳婦（付加量） ＋0.7 ＋0.8 ─`
