package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func VitaminB6(output string) {
	lines := strings.Split(vitaminB6Src, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 8}},
		{{Month: 9}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.VitaminB6, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 8
		a := ages[i]
		list = append(list,
			newVitaminB6(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+4]),
			newVitaminB6(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+4:j+8]),
		)
	}

	list2 := make([]data.VitaminB6, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		if d.EAR.Valid && d.RDA.Valid {
			list2 = append(list2,
				newVitaminB6WithOption(d, data.OptionEarlyPregnancy),
				newVitaminB6WithOption(d, data.OptionMidPregnancy),
				newVitaminB6WithOption(d, data.OptionLatePregnancy),
				newVitaminB6WithOption(d, data.OptionBreastfeeding),
			)
		}
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func VitaminB6List() []VitaminB6 {\n")
	g.MustWrite("    return []VitaminB6 {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newVitaminB6(g data.Gender, from, to data.Age, o data.Option, cols []string) data.VitaminB6 {
	return data.VitaminB6{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
		UL:     data.NilFloatFromString(cols[3]),
	}
}

func newVitaminB6WithOption(in data.VitaminB6, o data.Option) data.VitaminB6 {
	d := data.VitaminB6{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
		UL:     in.UL,
	}
	var ear, rda float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ear, rda = 0.2, 0.2
	case data.OptionBreastfeeding:
		ear, rda = 0.3, 0.3
	}
	if d.EAR.Valid {
		d.EAR.Float += ear
	}
	if d.RDA.Valid {
		d.RDA.Float += rda
	}
	return d
}

// PDF 267 ページの「ビタミン B6 の食事摂取基準」のコピペ
const vitaminB6Src = `0 ～ 5 （月） ─ ─ 0.2 ─ ─ ─ 0.2 ─
6 ～11（月） ─ ─ 0.3 ─ ─ ─ 0.3 ─
1 ～ 2 （歳） 0.4 0.5 ─ 10 0.4 0.5 ─ 10
3 ～ 5 （歳） 0.5 0.6 ─ 15 0.5 0.6 ─ 15
6 ～ 7 （歳） 0.7 0.8 ─ 20 0.6 0.7 ─ 20
8 ～ 9 （歳） 0.8 0.9 ─ 25 0.8 0.9 ─ 25
10～11（歳） 1.0 1.1 ─ 30 1.0 1.1 ─ 30
12～14（歳） 1.2 1.4 ─ 40 1.0 1.3 ─ 40
15～17（歳） 1.2 1.5 ─ 50 1.0 1.3 ─ 45
18～29（歳） 1.1 1.4 ─ 55 1.0 1.1 ─ 45
30～49（歳） 1.1 1.4 ─ 60 1.0 1.1 ─ 45
50～64（歳） 1.1 1.4 ─ 55 1.0 1.1 ─ 45
65～74（歳） 1.1 1.4 ─ 50 1.0 1.1 ─ 40
75 以上（歳） 1.1 1.4 ─ 50 1.0 1.1 ─ 40
妊婦（付加量） ＋0.2 ＋0.2 ─ ─
授乳婦（付加量） ＋0.3 ＋0.3 ─ ─`
