package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

// VitaminE は 214 ページの「ビタミン E の食事摂取基準」をパースして Go の構造体を作成します
func VitaminE(output string) {
	lines := strings.Split(vitaminESrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.VitaminE, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 4
		a := ages[i]
		list = append(list,
			newVitaminE(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+2]),
			newVitaminE(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+2:j+4]),
		)
	}

	list2 := make([]data.VitaminE, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newVitaminEWithOption(d, data.OptionEarlyPregnancy),
			newVitaminEWithOption(d, data.OptionMidPregnancy),
			newVitaminEWithOption(d, data.OptionLatePregnancy),
			newVitaminEWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func VitaminEList() []VitaminE {\n")
	g.MustWrite("    return []VitaminE {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newVitaminE(g data.Gender, from, to data.Age, o data.Option, cols []string) data.VitaminE {
	return data.VitaminE{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		AI:     data.NilFloatFromString(cols[0]),
		UL:     data.NilFloatFromString(cols[1]),
	}
}

func newVitaminEWithOption(in data.VitaminE, o data.Option) data.VitaminE {
	d := data.VitaminE{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		AI:     in.AI,
		UL:     in.UL,
	}
	var ai float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ai = 6.5
	case data.OptionBreastfeeding:
		ai = 7.0
	}
	if d.AI.Valid {
		d.AI.Float = ai
	}
	return d
}

const vitaminESrc = `0 ～ 5 （月） 3.0 ─ 3.0 ─
6 ～11（月） 4.0 ─ 4.0 ─
1 ～ 2 （歳） 3.0 150 3.0 150
3 ～ 5 （歳） 4.0 200 4.0 200
6 ～ 7 （歳） 5.0 300 5.0 300
8 ～ 9 （歳） 5.0 350 5.0 350
10～11（歳） 5.5 450 5.5 450
12～14（歳） 6.5 650 6.0 600
15～17（歳） 7.0 750 5.5 650
18～29（歳） 6.0 850 5.0 650
30～49（歳） 6.0 900 5.5 700
50～64（歳） 7.0 850 6.0 700
65～74（歳） 7.0 850 6.5 650
75 以上（歳） 6.5 750 6.5 650
妊　婦 6.5 ─
授乳婦 7.0 ─`
