package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func VitaminK(output string) {
	lines := strings.Split(vitaminKSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.VitaminK, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 2
		a := ages[i]
		list = append(list,
			newVitaminK(data.GenderMale, a[0], a[1], data.OptionNone, cols[j]),
			newVitaminK(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+1]),
		)
	}

	list2 := make([]data.VitaminK, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newVitaminKWithOption(d, data.OptionEarlyPregnancy),
			newVitaminKWithOption(d, data.OptionMidPregnancy),
			newVitaminKWithOption(d, data.OptionLatePregnancy),
			newVitaminKWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func VitaminKList() []VitaminK {\n")
	g.MustWrite("    return []VitaminK {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newVitaminK(g data.Gender, from, to data.Age, o data.Option, col string) data.VitaminK {
	return data.VitaminK{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		AI:     data.NilFloatFromString(col),
	}
}

func newVitaminKWithOption(in data.VitaminK, o data.Option) data.VitaminK {
	d := data.VitaminK{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		AI:     in.AI,
	}
	var ai float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy, data.OptionBreastfeeding:
		ai = 150
	}
	if d.AI.Valid {
		d.AI.Float = ai
	}
	return d
}

// PDF 215 ページの「ビタミン K の食事摂取基準」のコピペ
const vitaminKSrc = `0 ～ 5 （月） 4 4
6 ～11（月） 7 7
1 ～ 2 （歳） 50 60
3 ～ 5 （歳） 60 70
6 ～ 7 （歳） 80 90
8 ～ 9 （歳） 90 110
10～11（歳） 110 140
12～14（歳） 140 170
15～17（歳） 160 150
18～29（歳） 150 150
30～49（歳） 150 150
50～64（歳） 150 150
65～74（歳） 150 150
75 以上（歳） 150 150
妊　婦 150
授乳婦 150`
