package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

func VitaminC(output string) {
	lines := strings.Split(vitaminCSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 8}},
		{{Month: 9}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.VitaminC, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 6
		a := ages[i]
		list = append(list,
			newVitaminC(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+3]),
			newVitaminC(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+3:j+6]),
		)
	}

	list2 := make([]data.VitaminC, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		if d.EAR.Valid && d.RDA.Valid {
			list2 = append(list2,
				newVitaminCWithOption(d, data.OptionEarlyPregnancy),
				newVitaminCWithOption(d, data.OptionMidPregnancy),
				newVitaminCWithOption(d, data.OptionLatePregnancy),
				newVitaminCWithOption(d, data.OptionBreastfeeding),
			)
		}
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func VitaminCList() []VitaminC {\n")
	g.MustWrite("    return []VitaminC {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newVitaminC(g data.Gender, from, to data.Age, o data.Option, cols []string) data.VitaminC {
	return data.VitaminC{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
	}
}

func newVitaminCWithOption(in data.VitaminC, o data.Option) data.VitaminC {
	d := data.VitaminC{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
	}
	var ear, rda float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ear, rda = 10, 10
	case data.OptionBreastfeeding:
		ear, rda = 40, 45
	}
	if d.EAR.Valid {
		d.EAR.Float += ear
	}
	if d.RDA.Valid {
		d.RDA.Float += rda
	}
	return d
}

// PDF 272 ページの「ビタミン C の食事摂取基準」のコピペ
const vitaminCSrc = `0 ～ 5 （月） ─ ─ 40 ─ ─ 40
6 ～11（月） ─ ─ 40 ─ ─ 40
1 ～ 2 （歳） 35 40 ─ 35 40 ─
3 ～ 5 （歳） 40 50 ─ 40 50 ─
6 ～ 7 （歳） 50 60 ─ 50 60 ─
8 ～ 9 （歳） 60 70 ─ 60 70 ─
10～11（歳） 70 85 ─ 70 85 ─
12～14（歳） 85 100 ─ 85 100 ─
15～17（歳） 85 100 ─ 85 100 ─
18～29（歳） 85 100 ─ 85 100 ─
30～49（歳） 85 100 ─ 85 100 ─
50～64（歳） 85 100 ─ 85 100 ─
65～74（歳） 80 100 ─ 80 100 ─
75 以上（歳） 80 100 ─ 80 100 ─
妊　婦（付加量） ＋10 ＋10 ─
授乳婦（付加量） ＋40 ＋45 ─`
