package main

import (
	"fmt"
	"strings"

	"github.com/nirasan/syokuji-kijyun-2020/data"
	"github.com/nirasan/syokuji-kijyun-2020/tools"
)

// Zinc は 374 ページの「亜鉛の食事摂取基準」をパースして Go の構造体を作成します
func Zinc(output string) {
	lines := strings.Split(zincSrc, "\n")
	ages := [][]data.Age{
		{{Month: 0}, {Month: 5}},
		{{Month: 6}, {Month: 11}},
		{{Year: 1}, {Year: 2}},
		{{Year: 3}, {Year: 5}},
		{{Year: 6}, {Year: 7}},
		{{Year: 8}, {Year: 9}},
		{{Year: 10}, {Year: 11}},
		{{Year: 12}, {Year: 14}},
		{{Year: 15}, {Year: 17}},
		{{Year: 18}, {Year: 29}},
		{{Year: 30}, {Year: 49}},
		{{Year: 50}, {Year: 64}},
		{{Year: 65}, {Year: 74}},
		{{Year: 75}, {Year: 100}},
	}

	list := make([]data.Zinc, 0)
	for i := 0; i <= 13; i++ {
		line := strings.ReplaceAll(lines[i], ",", "")
		cols := strings.Split(line, " ")
		j := len(cols) - 8
		a := ages[i]
		list = append(list,
			newZinc(data.GenderMale, a[0], a[1], data.OptionNone, cols[j:j+4]),
			newZinc(data.GenderFemale, a[0], a[1], data.OptionNone, cols[j+4:j+8]),
		)
	}

	list2 := make([]data.Zinc, 0)
	for _, d := range list {
		if d.Gender != data.GenderFemale {
			continue
		}
		list2 = append(list2,
			newZincWithOption(d, data.OptionEarlyPregnancy),
			newZincWithOption(d, data.OptionMidPregnancy),
			newZincWithOption(d, data.OptionLatePregnancy),
			newZincWithOption(d, data.OptionBreastfeeding),
		)
	}

	list = append(list, list2...)

	g := tools.NewGenerator()
	g.MustWrite("// Code generated by \"cmd/generator/main.go\"; DO NOT EDIT.\n")
	g.MustWrite("package data\n")
	g.MustWrite("func ZincList() []Zinc {\n")
	g.MustWrite("    return []Zinc {\n")
	for _, d := range list {
		s := fmt.Sprintf("%#v,\n", d)
		s = strings.ReplaceAll(s, "data.", "")
		g.MustWrite(s)
	}
	g.MustWrite("    }\n")
	g.MustWrite("}\n")

	g.Generate(output)
}

func newZinc(g data.Gender, from, to data.Age, o data.Option, cols []string) data.Zinc {
	return data.Zinc{
		Gender: g,
		From:   from,
		To:     to,
		Option: o,
		EAR:    data.NilFloatFromString(cols[0]),
		RDA:    data.NilFloatFromString(cols[1]),
		AI:     data.NilFloatFromString(cols[2]),
		UL:     data.NilFloatFromString(cols[3]),
	}
}

func newZincWithOption(in data.Zinc, o data.Option) data.Zinc {
	d := data.Zinc{
		Gender: in.Gender,
		From:   in.From,
		To:     in.To,
		Option: o,
		EAR:    in.EAR,
		RDA:    in.RDA,
		AI:     in.AI,
		UL:     in.UL,
	}
	var ear, rda float64
	switch o {
	case data.OptionEarlyPregnancy, data.OptionMidPregnancy, data.OptionLatePregnancy:
		ear, rda = 1, 2
	case data.OptionBreastfeeding:
		ear, rda = 3, 4
	}
	if d.EAR.Valid {
		d.EAR.Float += ear
	}
	if d.RDA.Valid {
		d.RDA.Float += rda
	}
	return d
}

const zincSrc = `0 ～ 5 	（月） ─ ─ 2 ─ ─ ─ 2 ─
6 ～11（月） ─ ─ 3 ─ ─ ─ 3 ─
1 ～ 2 	（歳） 3 3 ─ ─ 2 3 ─ ─
3 ～ 5 	（歳） 3 4 ─ ─ 3 3 ─ ─
6 ～ 7 	（歳） 4 5 ─ ─ 3 4 ─ ─
8 ～ 9 	（歳） 5 6 ─ ─ 4 5 ─ ─
10～11（歳） 6 7 ─ ─ 5 6 ─ ─
12～14（歳） 9 10 ─ ─ 7 8 ─ ─
15～17（歳） 10 12 ─ ─ 7 8 ─ ─
18～29（歳） 9 11 ─ 40 7 8 ─ 35
30～49（歳） 9 11 ─ 45 7 8 ─ 35
50～64（歳） 9 11 ─ 45 7 8 ─ 35
65～74（歳） 9 11 ─ 40 7 8 ─ 35
75 以上（歳） 9 10 ─ 40 6 8 ─ 30
妊婦（付加量） ＋1 ＋2 ─ ─
授乳婦（付加量） ＋3 ＋4 ─ ─`
