// Code generated by "bin/carbohydrates/main.go"; DO NOT EDIT.
package pkg

func (c *Carbohydrates) Data() []CarbohydratesDatum {
	return []CarbohydratesDatum{
		CarbohydratesDatum{Gender: 0, Age: 0, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		CarbohydratesDatum{Gender: 1, Age: 0, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		CarbohydratesDatum{Gender: 0, Age: 1, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		CarbohydratesDatum{Gender: 1, Age: 1, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		CarbohydratesDatum{Gender: 0, Age: 2, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		CarbohydratesDatum{Gender: 1, Age: 2, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		CarbohydratesDatum{Gender: 0, Age: 3, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 3, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 4, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 4, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 5, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 5, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 6, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 6, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 7, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 7, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 8, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 8, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 9, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 9, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 10, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 10, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 11, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 11, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 12, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 12, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 13, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 13, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 0, Age: 14, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
		CarbohydratesDatum{Gender: 1, Age: 14, DGMax: NullFloat64{Value: 65, Valid: true}, DGMin: NullFloat64{Value: 50, Valid: true}},
	}
}
