// Code generated by "bin/dietary_fiber/main.go"; DO NOT EDIT.
package pkg

func (d *DietaryFiber) Data() []DietaryFiberDatum {
	return []DietaryFiberDatum{
		DietaryFiberDatum{Gender: 0, Age: 0, DGMin: NullFloat64{Value: 0, Valid: false}},
		DietaryFiberDatum{Gender: 1, Age: 0, DGMin: NullFloat64{Value: 0, Valid: false}},
		DietaryFiberDatum{Gender: 0, Age: 1, DGMin: NullFloat64{Value: 0, Valid: false}},
		DietaryFiberDatum{Gender: 1, Age: 1, DGMin: NullFloat64{Value: 0, Valid: false}},
		DietaryFiberDatum{Gender: 0, Age: 2, DGMin: NullFloat64{Value: 0, Valid: false}},
		DietaryFiberDatum{Gender: 1, Age: 2, DGMin: NullFloat64{Value: 0, Valid: false}},
		DietaryFiberDatum{Gender: 0, Age: 3, DGMin: NullFloat64{Value: 0, Valid: false}},
		DietaryFiberDatum{Gender: 1, Age: 3, DGMin: NullFloat64{Value: 0, Valid: false}},
		DietaryFiberDatum{Gender: 0, Age: 4, DGMin: NullFloat64{Value: 8, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 4, DGMin: NullFloat64{Value: 8, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 5, DGMin: NullFloat64{Value: 10, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 5, DGMin: NullFloat64{Value: 10, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 6, DGMin: NullFloat64{Value: 11, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 6, DGMin: NullFloat64{Value: 11, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 7, DGMin: NullFloat64{Value: 13, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 7, DGMin: NullFloat64{Value: 13, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 8, DGMin: NullFloat64{Value: 17, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 8, DGMin: NullFloat64{Value: 17, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 9, DGMin: NullFloat64{Value: 19, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 9, DGMin: NullFloat64{Value: 18, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 10, DGMin: NullFloat64{Value: 21, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 10, DGMin: NullFloat64{Value: 18, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 11, DGMin: NullFloat64{Value: 21, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 11, DGMin: NullFloat64{Value: 18, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 12, DGMin: NullFloat64{Value: 21, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 12, DGMin: NullFloat64{Value: 18, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 13, DGMin: NullFloat64{Value: 20, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 13, DGMin: NullFloat64{Value: 17, Valid: true}},
		DietaryFiberDatum{Gender: 0, Age: 14, DGMin: NullFloat64{Value: 20, Valid: true}},
		DietaryFiberDatum{Gender: 1, Age: 14, DGMin: NullFloat64{Value: 17, Valid: true}},
	}
}
