// Code generated by "bin/lipid/main.go"; DO NOT EDIT.
package pkg

func (l *Lipid) Data() []LipidDatum {
	return []LipidDatum{
		LipidDatum{Gender: 0, Age: 0, AI: NullFloat64{Value: 50, Valid: true}, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		LipidDatum{Gender: 1, Age: 0, AI: NullFloat64{Value: 50, Valid: true}, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		LipidDatum{Gender: 0, Age: 1, AI: NullFloat64{Value: 40, Valid: true}, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		LipidDatum{Gender: 1, Age: 1, AI: NullFloat64{Value: 40, Valid: true}, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		LipidDatum{Gender: 0, Age: 2, AI: NullFloat64{Value: 40, Valid: true}, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		LipidDatum{Gender: 1, Age: 2, AI: NullFloat64{Value: 40, Valid: true}, DGMax: NullFloat64{Value: 0, Valid: false}, DGMin: NullFloat64{Value: 0, Valid: false}},
		LipidDatum{Gender: 0, Age: 3, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 3, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 4, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 4, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 5, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 5, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 6, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 6, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 7, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 7, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 8, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 8, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 9, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 9, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 10, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 10, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 11, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 11, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 12, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 12, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 13, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 13, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 0, Age: 14, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
		LipidDatum{Gender: 1, Age: 14, AI: NullFloat64{Value: 0, Valid: false}, DGMax: NullFloat64{Value: 30, Valid: true}, DGMin: NullFloat64{Value: 20, Valid: true}},
	}
}
