// Code generated by "bin/omega3_fatty_acids/main.go"; DO NOT EDIT.
package pkg

func (o *Omega3FattyAcids) Data() []Omega3FattyAcidsDatum {
	return []Omega3FattyAcidsDatum{
		Omega3FattyAcidsDatum{Gender: 0, Age: 0, AI: NullFloat64{Value: 0.9, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 0, AI: NullFloat64{Value: 0.9, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 1, AI: NullFloat64{Value: 0.8, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 1, AI: NullFloat64{Value: 0.8, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 2, AI: NullFloat64{Value: 0.8, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 2, AI: NullFloat64{Value: 0.8, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 3, AI: NullFloat64{Value: 0.7, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 3, AI: NullFloat64{Value: 0.8, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 4, AI: NullFloat64{Value: 1.1, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 4, AI: NullFloat64{Value: 1, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 5, AI: NullFloat64{Value: 1.5, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 5, AI: NullFloat64{Value: 1.3, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 6, AI: NullFloat64{Value: 1.5, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 6, AI: NullFloat64{Value: 1.3, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 7, AI: NullFloat64{Value: 1.6, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 7, AI: NullFloat64{Value: 1.6, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 8, AI: NullFloat64{Value: 1.9, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 8, AI: NullFloat64{Value: 1.6, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 9, AI: NullFloat64{Value: 2.1, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 9, AI: NullFloat64{Value: 1.6, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 10, AI: NullFloat64{Value: 2, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 10, AI: NullFloat64{Value: 1.6, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 11, AI: NullFloat64{Value: 2, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 11, AI: NullFloat64{Value: 1.6, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 12, AI: NullFloat64{Value: 2.2, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 12, AI: NullFloat64{Value: 1.9, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 13, AI: NullFloat64{Value: 2.2, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 13, AI: NullFloat64{Value: 2, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 0, Age: 14, AI: NullFloat64{Value: 2.1, Valid: true}},
		Omega3FattyAcidsDatum{Gender: 1, Age: 14, AI: NullFloat64{Value: 1.8, Valid: true}},
	}
}
