// Code generated by "bin/omega6_fatty_acids/main.go"; DO NOT EDIT.
package pkg

func (o *Omega6FattyAcids) Data() []Omega6FattyAcidsDatum {
	return []Omega6FattyAcidsDatum{
		Omega6FattyAcidsDatum{Gender: 0, Age: 0, AI: NullFloat64{Value: 4, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 0, AI: NullFloat64{Value: 4, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 1, AI: NullFloat64{Value: 4, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 1, AI: NullFloat64{Value: 4, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 2, AI: NullFloat64{Value: 4, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 2, AI: NullFloat64{Value: 4, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 3, AI: NullFloat64{Value: 4, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 3, AI: NullFloat64{Value: 4, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 4, AI: NullFloat64{Value: 6, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 4, AI: NullFloat64{Value: 6, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 5, AI: NullFloat64{Value: 8, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 5, AI: NullFloat64{Value: 7, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 6, AI: NullFloat64{Value: 8, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 6, AI: NullFloat64{Value: 7, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 7, AI: NullFloat64{Value: 10, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 7, AI: NullFloat64{Value: 8, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 8, AI: NullFloat64{Value: 11, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 8, AI: NullFloat64{Value: 9, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 9, AI: NullFloat64{Value: 13, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 9, AI: NullFloat64{Value: 9, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 10, AI: NullFloat64{Value: 11, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 10, AI: NullFloat64{Value: 8, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 11, AI: NullFloat64{Value: 10, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 11, AI: NullFloat64{Value: 8, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 12, AI: NullFloat64{Value: 10, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 12, AI: NullFloat64{Value: 8, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 13, AI: NullFloat64{Value: 9, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 13, AI: NullFloat64{Value: 8, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 0, Age: 14, AI: NullFloat64{Value: 8, Valid: true}},
		Omega6FattyAcidsDatum{Gender: 1, Age: 14, AI: NullFloat64{Value: 7, Valid: true}},
	}
}
