// Code generated by "bin/saturated_fatty_acids/main.go"; DO NOT EDIT.
package pkg

func (s *SaturatedFattyAcids) Data() []SaturatedFattyAcidsDatum {
	return []SaturatedFattyAcidsDatum{
		SaturatedFattyAcidsDatum{Gender: 0, Age: 0, DGMax: NullFloat64{Value: 0, Valid: false}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 0, DGMax: NullFloat64{Value: 0, Valid: false}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 1, DGMax: NullFloat64{Value: 0, Valid: false}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 1, DGMax: NullFloat64{Value: 0, Valid: false}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 2, DGMax: NullFloat64{Value: 0, Valid: false}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 2, DGMax: NullFloat64{Value: 0, Valid: false}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 3, DGMax: NullFloat64{Value: 0, Valid: false}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 3, DGMax: NullFloat64{Value: 0, Valid: false}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 4, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 4, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 5, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 5, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 6, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 6, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 7, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 7, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 8, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 8, DGMax: NullFloat64{Value: 10, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 9, DGMax: NullFloat64{Value: 8, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 9, DGMax: NullFloat64{Value: 8, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 10, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 10, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 11, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 11, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 12, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 12, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 13, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 13, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 0, Age: 14, DGMax: NullFloat64{Value: 7, Valid: true}},
		SaturatedFattyAcidsDatum{Gender: 1, Age: 14, DGMax: NullFloat64{Value: 7, Valid: true}},
	}
}
