// Code generated by "bin/vitamin_a/main.go"; DO NOT EDIT.
package pkg

func (vit *VitaminE) Data() []VitaminEDatum {
	return []VitaminEDatum{
		VitaminEDatum{Gender: 0, Age: 0, AI: NullFloat64{Value: 3, Valid: true}, UL: NullFloat64{Value: 0, Valid: false}},
		VitaminEDatum{Gender: 1, Age: 0, AI: NullFloat64{Value: 3, Valid: true}, UL: NullFloat64{Value: 0, Valid: false}},
		VitaminEDatum{Gender: 0, Age: 1, AI: NullFloat64{Value: 4, Valid: true}, UL: NullFloat64{Value: 0, Valid: false}},
		VitaminEDatum{Gender: 1, Age: 1, AI: NullFloat64{Value: 4, Valid: true}, UL: NullFloat64{Value: 0, Valid: false}},
		VitaminEDatum{Gender: 0, Age: 2, AI: NullFloat64{Value: 4, Valid: true}, UL: NullFloat64{Value: 0, Valid: false}},
		VitaminEDatum{Gender: 1, Age: 2, AI: NullFloat64{Value: 4, Valid: true}, UL: NullFloat64{Value: 0, Valid: false}},
		VitaminEDatum{Gender: 0, Age: 3, AI: NullFloat64{Value: 3, Valid: true}, UL: NullFloat64{Value: 150, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 3, AI: NullFloat64{Value: 3, Valid: true}, UL: NullFloat64{Value: 150, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 4, AI: NullFloat64{Value: 4, Valid: true}, UL: NullFloat64{Value: 200, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 4, AI: NullFloat64{Value: 4, Valid: true}, UL: NullFloat64{Value: 200, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 5, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 300, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 5, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 300, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 6, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 350, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 6, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 350, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 7, AI: NullFloat64{Value: 5.5, Valid: true}, UL: NullFloat64{Value: 450, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 7, AI: NullFloat64{Value: 5.5, Valid: true}, UL: NullFloat64{Value: 450, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 8, AI: NullFloat64{Value: 6.5, Valid: true}, UL: NullFloat64{Value: 650, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 8, AI: NullFloat64{Value: 6, Valid: true}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 9, AI: NullFloat64{Value: 7, Valid: true}, UL: NullFloat64{Value: 750, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 9, AI: NullFloat64{Value: 5.5, Valid: true}, UL: NullFloat64{Value: 650, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 10, AI: NullFloat64{Value: 6, Valid: true}, UL: NullFloat64{Value: 850, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 10, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 650, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 11, AI: NullFloat64{Value: 6, Valid: true}, UL: NullFloat64{Value: 900, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 11, AI: NullFloat64{Value: 5.5, Valid: true}, UL: NullFloat64{Value: 700, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 12, AI: NullFloat64{Value: 7, Valid: true}, UL: NullFloat64{Value: 850, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 12, AI: NullFloat64{Value: 6, Valid: true}, UL: NullFloat64{Value: 700, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 13, AI: NullFloat64{Value: 7, Valid: true}, UL: NullFloat64{Value: 850, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 13, AI: NullFloat64{Value: 6.5, Valid: true}, UL: NullFloat64{Value: 650, Valid: true}},
		VitaminEDatum{Gender: 0, Age: 14, AI: NullFloat64{Value: 6.5, Valid: true}, UL: NullFloat64{Value: 750, Valid: true}},
		VitaminEDatum{Gender: 1, Age: 14, AI: NullFloat64{Value: 6.5, Valid: true}, UL: NullFloat64{Value: 650, Valid: true}},
	}
}
