// Code generated by "bin/vitamin_a/main.go"; DO NOT EDIT.
package pkg

func (vit *VitaminK) Data() []VitaminKDatum {
	return []VitaminKDatum{
		VitaminKDatum{Gender: 0, Age: 0, AI: NullFloat64{Value: 4, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 0, AI: NullFloat64{Value: 4, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 1, AI: NullFloat64{Value: 7, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 1, AI: NullFloat64{Value: 7, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 2, AI: NullFloat64{Value: 7, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 2, AI: NullFloat64{Value: 7, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 3, AI: NullFloat64{Value: 50, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 3, AI: NullFloat64{Value: 60, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 4, AI: NullFloat64{Value: 60, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 4, AI: NullFloat64{Value: 70, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 5, AI: NullFloat64{Value: 80, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 5, AI: NullFloat64{Value: 90, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 6, AI: NullFloat64{Value: 90, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 6, AI: NullFloat64{Value: 110, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 7, AI: NullFloat64{Value: 110, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 7, AI: NullFloat64{Value: 140, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 8, AI: NullFloat64{Value: 140, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 8, AI: NullFloat64{Value: 170, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 9, AI: NullFloat64{Value: 160, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 9, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 10, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 10, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 11, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 11, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 12, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 12, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 13, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 13, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 0, Age: 14, AI: NullFloat64{Value: 150, Valid: true}},
		VitaminKDatum{Gender: 1, Age: 14, AI: NullFloat64{Value: 150, Valid: true}},
	}
}
