// Code generated by "bin/vitamin_a/main.go"; DO NOT EDIT.
package pkg

func (vit *VitaminA) Data() []VitaminADatum {
	return []VitaminADatum{
		VitaminADatum{Gender: 0, Age: 0, EAR: NullFloat64{Value: 0, Valid: false}, RDA: NullFloat64{Value: 0, Valid: false}, AI: NullFloat64{Value: 300, Valid: true}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminADatum{Gender: 1, Age: 0, EAR: NullFloat64{Value: 0, Valid: false}, RDA: NullFloat64{Value: 0, Valid: false}, AI: NullFloat64{Value: 300, Valid: true}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminADatum{Gender: 0, Age: 1, EAR: NullFloat64{Value: 0, Valid: false}, RDA: NullFloat64{Value: 0, Valid: false}, AI: NullFloat64{Value: 400, Valid: true}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminADatum{Gender: 1, Age: 1, EAR: NullFloat64{Value: 0, Valid: false}, RDA: NullFloat64{Value: 0, Valid: false}, AI: NullFloat64{Value: 400, Valid: true}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminADatum{Gender: 0, Age: 2, EAR: NullFloat64{Value: 0, Valid: false}, RDA: NullFloat64{Value: 0, Valid: false}, AI: NullFloat64{Value: 400, Valid: true}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminADatum{Gender: 1, Age: 2, EAR: NullFloat64{Value: 0, Valid: false}, RDA: NullFloat64{Value: 0, Valid: false}, AI: NullFloat64{Value: 400, Valid: true}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminADatum{Gender: 0, Age: 3, EAR: NullFloat64{Value: 300, Valid: true}, RDA: NullFloat64{Value: 400, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminADatum{Gender: 1, Age: 3, EAR: NullFloat64{Value: 250, Valid: true}, RDA: NullFloat64{Value: 350, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 600, Valid: true}},
		VitaminADatum{Gender: 0, Age: 4, EAR: NullFloat64{Value: 350, Valid: true}, RDA: NullFloat64{Value: 450, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 700, Valid: true}},
		VitaminADatum{Gender: 1, Age: 4, EAR: NullFloat64{Value: 350, Valid: true}, RDA: NullFloat64{Value: 500, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 850, Valid: true}},
		VitaminADatum{Gender: 0, Age: 5, EAR: NullFloat64{Value: 300, Valid: true}, RDA: NullFloat64{Value: 400, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 950, Valid: true}},
		VitaminADatum{Gender: 1, Age: 5, EAR: NullFloat64{Value: 300, Valid: true}, RDA: NullFloat64{Value: 400, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 1200, Valid: true}},
		VitaminADatum{Gender: 0, Age: 6, EAR: NullFloat64{Value: 350, Valid: true}, RDA: NullFloat64{Value: 500, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 1200, Valid: true}},
		VitaminADatum{Gender: 1, Age: 6, EAR: NullFloat64{Value: 350, Valid: true}, RDA: NullFloat64{Value: 500, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 1500, Valid: true}},
		VitaminADatum{Gender: 0, Age: 7, EAR: NullFloat64{Value: 450, Valid: true}, RDA: NullFloat64{Value: 600, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 1500, Valid: true}},
		VitaminADatum{Gender: 1, Age: 7, EAR: NullFloat64{Value: 400, Valid: true}, RDA: NullFloat64{Value: 600, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 1900, Valid: true}},
		VitaminADatum{Gender: 0, Age: 8, EAR: NullFloat64{Value: 550, Valid: true}, RDA: NullFloat64{Value: 800, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2100, Valid: true}},
		VitaminADatum{Gender: 1, Age: 8, EAR: NullFloat64{Value: 500, Valid: true}, RDA: NullFloat64{Value: 700, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2500, Valid: true}},
		VitaminADatum{Gender: 0, Age: 9, EAR: NullFloat64{Value: 650, Valid: true}, RDA: NullFloat64{Value: 900, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2500, Valid: true}},
		VitaminADatum{Gender: 1, Age: 9, EAR: NullFloat64{Value: 500, Valid: true}, RDA: NullFloat64{Value: 650, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2800, Valid: true}},
		VitaminADatum{Gender: 0, Age: 10, EAR: NullFloat64{Value: 600, Valid: true}, RDA: NullFloat64{Value: 850, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 1, Age: 10, EAR: NullFloat64{Value: 450, Valid: true}, RDA: NullFloat64{Value: 650, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 0, Age: 11, EAR: NullFloat64{Value: 650, Valid: true}, RDA: NullFloat64{Value: 900, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 1, Age: 11, EAR: NullFloat64{Value: 500, Valid: true}, RDA: NullFloat64{Value: 700, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 0, Age: 12, EAR: NullFloat64{Value: 650, Valid: true}, RDA: NullFloat64{Value: 900, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 1, Age: 12, EAR: NullFloat64{Value: 500, Valid: true}, RDA: NullFloat64{Value: 700, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 0, Age: 13, EAR: NullFloat64{Value: 600, Valid: true}, RDA: NullFloat64{Value: 850, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 1, Age: 13, EAR: NullFloat64{Value: 500, Valid: true}, RDA: NullFloat64{Value: 700, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 0, Age: 14, EAR: NullFloat64{Value: 550, Valid: true}, RDA: NullFloat64{Value: 800, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
		VitaminADatum{Gender: 1, Age: 14, EAR: NullFloat64{Value: 450, Valid: true}, RDA: NullFloat64{Value: 650, Valid: true}, AI: NullFloat64{Value: 0, Valid: false}, UL: NullFloat64{Value: 2700, Valid: true}},
	}
}
