// Code generated by "bin/vitamin_a/main.go"; DO NOT EDIT.
package pkg

func (vit *VitaminD) Data() []VitaminDDatum {
	return []VitaminDDatum{
		VitaminDDatum{Gender: 0, Age: 0, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 25, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 0, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 25, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 1, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 25, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 1, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 25, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 2, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 25, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 2, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 25, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 3, AI: NullFloat64{Value: 3, Valid: true}, UL: NullFloat64{Value: 20, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 3, AI: NullFloat64{Value: 3.5, Valid: true}, UL: NullFloat64{Value: 20, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 4, AI: NullFloat64{Value: 3.5, Valid: true}, UL: NullFloat64{Value: 30, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 4, AI: NullFloat64{Value: 4, Valid: true}, UL: NullFloat64{Value: 30, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 5, AI: NullFloat64{Value: 4.5, Valid: true}, UL: NullFloat64{Value: 30, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 5, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 30, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 6, AI: NullFloat64{Value: 5, Valid: true}, UL: NullFloat64{Value: 40, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 6, AI: NullFloat64{Value: 6, Valid: true}, UL: NullFloat64{Value: 40, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 7, AI: NullFloat64{Value: 6.5, Valid: true}, UL: NullFloat64{Value: 60, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 7, AI: NullFloat64{Value: 8, Valid: true}, UL: NullFloat64{Value: 60, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 8, AI: NullFloat64{Value: 8, Valid: true}, UL: NullFloat64{Value: 80, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 8, AI: NullFloat64{Value: 9.5, Valid: true}, UL: NullFloat64{Value: 80, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 9, AI: NullFloat64{Value: 9, Valid: true}, UL: NullFloat64{Value: 90, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 9, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 90, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 10, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 10, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 11, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 11, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 12, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 12, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 13, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 13, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 0, Age: 14, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
		VitaminDDatum{Gender: 1, Age: 14, AI: NullFloat64{Value: 8.5, Valid: true}, UL: NullFloat64{Value: 100, Valid: true}},
	}
}
